name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  python-version:
    description: 'Override version of python used to run ape- default 3.10'
    required: False
    default: '3.10'
  ape-version-pin:
    description: 'Override version of eth-ape, can also use a `git+` prefixed value'
    required: False
  ape-plugins-list:
    description: 'Space seperated list of plugins to install with relevant pinning applied'
    required: False
    default: ''

outputs:
  ape-version:
    description: 'The version of Ape installed'

runs:
  using: 'composite'

  steps:
    - uses: actions/cache@v4
      name: Compilers cache
      with:
        path: |
          /home/runner/.solcx
          /home/runner/.vvm/vyper-*
        key: ${{ runner.os }}-compiler-cache

    - uses: actions/cache@v4
      name: Build cache
      with:
        path: |
          ${{ github.workspace }}/.build
        key: ${{ runner.os }}-build-cache

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set pip cache directory path
      id: pip-cache-dir-path
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Determine ape version to use
      id: determine-version
      run: |
        if [[ "${{ inputs.ape-version-pin }}" != "" && "${{ inputs.ape-version-pin }}" != "''" ]]; then
          echo "ape-version=${{ inputs.ape-version-pin }}" >> $GITHUB_OUTPUT
        else
          latest_version=$(curl -s https://pypi.org/pypi/eth-ape/json | jq -r '.info.version')
          echo "ape-version=${latest_version}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Restore pip cache
      uses: actions/cache@v4
      id: pip-cache
      with:
        path: |
          ${{ steps.pip-cache-dir-path.outputs.dir }}
        key: ${{ inputs.python-version }}-pip-${{ steps.determine-version.outputs.ape-version }}

    - name: Install Ape
      run: |
        pip install --upgrade pip
        if [[ "${{ steps.determine-version.outputs.ape-version }}" == git+* ]]
        then
          echo "INFO: Installing from a remote git version."
          pip install ${{ steps.determine-version.outputs.ape-version }}
        else
          version_regex='^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
          if [[ ${{ steps.determine-version.outputs.ape-version }} =~ $version_regex ]]; then
            # Allows for excluding `==` to `ape-version-pin`
            echo "Installing with == prefix"
            pip install eth-ape==${{ steps.determine-version.outputs.ape-version }}
          else
            echo "Installing using given constraints"
            pip install eth-ape${{ steps.determine-version.outputs.ape-version }}
          fi
        fi
      shell: bash

    - name: Check ape-config.yaml exists
      id: check-ape-config-yaml
      uses: andstor/file-existence-action@v3
      with:
        files: 'ape-config.yaml'
      
    - name: Check version specs in config
      id: check-plugin-version-specs
      run: |
        if [[ "${{ steps.check-ape-config-yaml.outputs.files_exists }}" == "true" ]]; then
          version_present=$(sed -n '/^plugins:/,/^[^ ]/{/version:/p;}' "ape-config.yaml" | grep -c version || true)
          if [[ -z "${version_present}" ]]; then
            echo "version_present=0" >> $GITHUB_OUTPUT
          else
            echo "version_present=1" >> $GITHUB_OUTPUT
          fi
        else
          echo "version_present=0" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Install Plugins
      run: |
        if [[ "${{ steps.check-plugin-version-specs.outputs.version_present }}" == "1" ]] && [[ -z "${{ inputs.ape-plugins-list }}" ]]; then
          plugins_value="."
        elif [[ -z "${{ inputs.ape-plugins-list }}" ]]; then
          plugins_value="--upgrade ."
        else
          plugins_value="${{ inputs.ape-plugins-list }}"
        fi

        ape plugins install $plugins_value

      shell: bash
    - name: Check requirments.txt exists
      id: check-requirements-txt
      uses: andstor/file-existence-action@v3
      with:
        files: 'requirements.txt'
  
    - name: Install requirements.txt
      run: pip install -r requirements.txt
      shell: bash
      if: steps.check-requirements-txt.outputs.files_exists == 'true'

    - name: Ensure cache directories exist
      shell: bash
      run: |
        # NOTE: Workaround for an unrepressible warning
        # in the cache action:
        # https://github.com/actions/cache/issues/1241

        if [ ! -d "/home/runner/.solcx" ]; then
          mkdir -p "/home/runner/.solcx"
          echo "Solcx directory created."
        fi
        if [ ! -d "/home/runner/.vvm" ]; then
          mkdir -p "/home/runner/.vvm"
          echo "VVM directory created."
        fi
        if [ ! -d "${{ github.workspace }}/.build" ]; then
          mkdir -p "${{ github.workspace }}/.build"
          echo ".build directory created."
        fi
